### ISSUE TITLE
Non-integer offsets for hours

### ISSUE THREAD

**Issue by Knusper** [whiteinge/dotfiles#19]
Another fun problem I discovered while working with people in India and Australia: Non-integer hour offsets.
Any idea how `timebuddy` could be modified here...

**Comment by whiteinge** [comment]
Hm. I might need an example to play with to see what you mean. Offhand, I think all offsets should be non-integers. E.g.:
```
% TZ=MST7MDT date +%z
-0700
% TZ=Australia/Brisbane date +%z
+1000
```
Is `date` producing something different for you, or am I misunderstanding?

**Comment by Knusper** [comment]
```
$ TZ=Australia/North date +%z
+0930
```

**Comment by whiteinge** [comment]
Thanks for the details (and finding the edge-case!). I didn't know time zones could be offset at minutes too. Crazy stuff.

Updating the script to always output minutes is a trivial change:
```diff
diff --git a/bin/timebuddy b/bin/timebuddy
index 4999d6f..0d73e18 100755
--- a/bin/timebuddy
+++ b/bin/timebuddy
@@ -46,7 +46,7 @@ get_hours () {
     printf '%s\n' 00 01 02 03 04 05 06 07 08 09 10 11 12 \
             13 14 15 16 17 18 19 20 21 22 23 |
         xargs -I{} printf 'TZ="%s" %s {}:00 %s\n' "$cur" "$datestr" "$offset" |
-        TZ="$tgt" date +'%a %H' -f - |
+        TZ="$tgt" date +'%a %R' -f - |
         fmt_hours
     printf ' - %s\n' "$tgt"
 }
```

Sample output:
```
% timebuddy EST5EDT Australia/North Pacific/Chatham
Sat  00:00 01:00 02:00 03:00 04:00 05:00 06:00 07:00 08:00 09:00 10:00 11:00 12:00 13:00 14:00 15:00 16:00 17:00 18:00 19:00 20:00 21:00 22:00 23:00  Sat - America/Denver
Sat  02:00 03:00 04:00 05:00 06:00 07:00 08:00 09:00 10:00 11:00 12:00 13:00 14:00 15:00 16:00 17:00 18:00 19:00 20:00 21:00 22:00 23:00 00:00 01:00  Sun - EST5EDT
Sat  16:30 17:30 18:30 19:30 20:30 21:30 22:30 23:30 00:30 01:30 02:30 03:30 04:30 05:30 06:30 07:30 08:30 09:30 10:30 11:30 12:30 13:30 14:30 15:30  Sun - Australia/North
Sat  20:45 21:45 22:45 23:45 00:45 01:45 02:45 03:45 04:45 05:45 06:45 07:45 08:45 09:45 10:45 11:45 12:45 13:45 14:45 15:45 16:45 17:45 18:45 19:45  Sun - Pacific/Chatham
```

That works but produces very noisy & wide output. I wrote a branch to output minutes only conditionally if any of the target time zones have a minutes-level offset (#20) because I wanted to see if I liked it. I don't :stuck_out_tongue:. It's just too noisy but you're welcome to grab that branch if it's helpful.

What if we were to output a special marker for any time zones with a minutes-level offset (#21). Succinct but hopefully noticeable. What do you think about the following output?
```
Sat  01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23  Sat - America/Denver
Sat  03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 00 01  Sun - EST5EDT
Sat  17 18 19 20 21 22 23 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15  Sun - (+0930) Australia/North
Sat  21 22 23 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19  Sun - (+1345) Pacific/Chatham
```

**Comment by Knusper** [comment]
Thanks so much for investigating and pointing me in the right direction.
